name: Build and Deploy SAM2 API

on:
  push:
    branches: [main]
    tags:
      - "v*"
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64
          build-args: |
            GITHUB_TOKEN=${{ secrets.REPO_GITHUB_TOKEN }}

  deployment-info:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: RunPod Deployment Instructions
        run: |
          echo "🚀 Docker image built and pushed successfully!"
          echo ""
          echo "📋 To deploy on RunPod:"
          echo "1. Go to https://runpod.io"
          echo "2. Create a new pod with a GPU template"
          echo "3. Use this Docker image: ghcr.io/${{ github.repository }}:latest"
          echo "4. Set container port: 8000"
          echo "5. Expose HTTP port: 8000"
          echo ""
          echo "🔧 Or use this docker run command on RunPod:"
          echo "docker run -d -p 8000:8000 --gpus all ghcr.io/${{ github.repository }}:latest"
          echo ""
          echo "🏥 Health check endpoint: http://your-pod-url:8000/health"
